#!/usr/bin/env bash
# This script displays the visitor IP and HTTP status code from Apache log file
awk '{print $1, $9}' /dev/stdin
git add loops_conditions_and_parsing/13-lets_parse_apache_logs
git commit -m "Fix 13-lets_parse_apache_logs: read from stdin"
git push origin master
Ctrl+C
cat > loops_conditions_and_parsing/13-lets_parse_apache_logs << 'EOF'
#!/usr/bin/env bash
# This script displays the visitor IP and HTTP status code from Apache log file
awk '{print $1, $9}' /dev/stdin
