#!/bin/bash
water="water"
stir="stir."
bestchol="bestchol"

w=0
for ((i=0; i<${#WATER}; i++))
do
c="${WATER:$i:1}"
pos="${water%%$c*}"
w=$((w * 5 + ${#pos}))
done

s=0
for ((i=0; i<${#STIR}; i++))
do
c="${STIR:$i:1}"
pos="${stir%%$c*}"
s=$((s * 5 + ${#pos}))
done

sum=$((w + s))

result=""
while [ $sum -gt 0 ]
do
result="${bestchol:$((sum % 8)):1}$result"
sum=$((sum / 8))
done

echo "$result"
