#!/bin/bash
water="water"
stir="stir."
bestchol="bestchol"

w=0
i=0
while [ $i -lt ${#WATER} ]
do
c="${WATER:$i:1}"
pos="${water%%$c*}"
w=$((w * 5 + ${#pos}))
i=$((i + 1))
done

s=0
i=0
while [ $i -lt ${#STIR} ]
do
c="${STIR:$i:1}"
pos="${stir%%$c*}"
s=$((s * 5 + ${#pos}))
i=$((i + 1))
done

sum=$((w + s))
result=""
while [ $sum -gt 0 ]
do
result="${bestchol:$((sum % 8)):1}$result"
sum=$((sum / 8))
done

echo "$result"
