#!/bin/bash
python3 -c "w=sum('water'.index(c)*5**i for i,c in enumerate(reversed('$WATER')));s=sum('stir.'.index(c)*5**i for i,c in enumerate(reversed('$STIR')));t=w+s;r='';r=r or'b' if not t else '';exec(\"while t:r='bestchol'[t%8]+r;t//=8\");print(r)"
